### ISSUE TITLE
how can I disable my virtual keyboard? 

### ISSUE THREAD

**Issue by sparrowyang** [joshuakraemer/sddm-theme-dialog#1]
hi~
I used this them int the plasma, I think it is very cool and simple. 
I very love  this them. But in my computer, ubuntu 20.04, when I in login , the virtual keyboard is auto show as default, and it full of my screen.

how can I disable  my virtual keyboard?

**Comment by joshuakraemer** [comment]
This is a bug in SDDM, see https://github.com/sddm/sddm/issues/952.

You can disable the virtual keyboard in SDDM's config file `/etc/sddm.conf`. In the `[General]` section, replace `InputMethod=qtvirtualkeyboard` with `InputMethod=` (empty string).

Or if you don't need the virtual keyboard at all, you can just remove its package (I think it's the "qtvirtualkeyboard-plugin" package in Ubuntu).

**Comment by Tri4c3** [comment]
In Ubuntu 26 LTS, there is no /etc/sddm.conf file, and creating one and editing it with that configuration doesn't do any good :/
