### ISSUE TITLE
Scaling?

### ISSUE THREAD

**Issue by ghost** [joshuakraemer/sddm-theme-dialog#2]
I love this theme but it look too small on my laptop screen. My laptop screen is 1900x1200.

**Comment by joshuakraemer** [comment]
It should scale automatically if the screen density (dpi) is detected or configured correctly. What display server and video driver do you use?

**Comment by joshuakraemer** [comment]
The following works for me to make the SDDM greeter as well as other QT applications scale correctly on a high-dpi screen with X11.

1. Enable QT scaling by setting the environment variable "QT_AUTO_SCREEN_SCALE_FACTOR" to "1". To set that variable system wide (which is necessary to make it work in SDDM), add the following to the file "/etc/environment":

	```
	QT_AUTO_SCREEN_SCALE_FACTOR=1
	```

2. If X11 does not detect the screen resolution correctly, configure it manually by creating a file "/etc/X11/xorg.conf.d/10-screen.conf" with the following contents:

	```
	Section "Screen"
		Identifier "Default Screen"
		Option "DPI" "288 x 288"
	EndSection
	```

	That DPI option is only available with the proprietary Nvidia display driver, though. With other drivers, you have to configure the screen size instead, for example like this (values in mm):

	```
	Section "Monitor"
		Identifier "eDP1"
		DisplaySize 339 191
	EndSection
	```
